services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  backend:
    build:
      context: ./to-do-backend
      dockerfile: ../dockerfiles/backend.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/to-do
#    env_file:
#      - ./.env/backend.env
  frontend:
    build:
      context: ./to-do-frontend
      dockerfile: ../dockerfiles/frontend.dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
      - mongodb